displayName=FC Stat Checker
author=WildSwab
description=Check if Friends Chat members meet a skill requirement
tags=friends,chat,fc,stats,hiscores,skill
plugins=com.fcstatchecker.FcStatCheckerPlugin
build=standard